---
title: "Calendar"
---


The calendar below lists the tentative dates of the readings, group quizzes, and course activities. Exam due dates and quiz dates are also provided. All individual exams are due by 9:45am. These dates are subject to change at the instructor's discretion.

As part of the course, there may be articles, papers, etc. that you will need to read during the semester. Most of the articles themselves are accessible through the [University of Minnesota library website](http://www.lib.umn.edu). In order to access the full text of some of the articles, you will need to log in using your University x500 username and password. More detailed information, including references or links to specific readings, are linked under the day's "Reading".

<br /><br />


<table class="table">
<caption>Schedule of Content for EPSY 3264, including topics, readings, class activities, and assessments.</caption>
<thead>
<tr>
<th style="width:5%;" id="blank"></th>
<th style="width:10%; text-align:center;" id="day">Day</th>
<th style="width:10%;" id="date">Date</th>
<th style="width:35%;" id="reading">Reading</th>
<th style="width:50%;" id="activity">Class Activity/Assessment</th>
</tr>
</thead>

<tbody>

<tr>
<td style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">1</td>
<td style="vertical-align:middle;" headers="date">Jan. 22</td>
<td style="vertical-align:middle;" headers="reading">
  [Introduction](https://zief0002.github.io/statistical-thinking/01-introduction.html)
</td>
<td style="vertical-align:middle;" headers="activity">Welcome to 3264!</td>
</tr>



<!-- Unit 01: MODELING AND SIMULATION -->

<tr>
<td style="height: 50px; vertical-align: bottom;" colspan="5" headers="blank day date reading activity">**UNIT 01: MODELING AND SIMULATION**</td>
</tr>


<tr>
<td style="vertical-align:middle;" rowspan=2 headers="blank"></td>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="day">2</td>
<td style="vertical-align:middle;" rowspan=2 headers="date">Jan. 27</td>
<td style="vertical-align:middle;" rowspan=2 headers="reading">
  [Modeling &amp; Simulation](https://zief0002.github.io/statistical-thinking/02-modeling-and-simulation.html)
</td>
<td style="vertical-align:middle;" headers="activity">Spotify Playlists</td>
</tr>

<tr>
<td style="background-color: #fffdc0" headers="activity">**Exit Ticket: Download TinkerPlots**</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">3</td>
<td style="vertical-align:middle;" headers="date">Jan. 29</td>
<td style="vertical-align:middle;" headers="reading">
  [Watch TinkerPlots&trade; Basics video](readings/03-learning-tp.html)
</td>
<td style="vertical-align:middle;" headers="activity">Learning to Use TinkerPlots&trade</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">4</td>
<td style="vertical-align:middle;" headers="date">Feb. 03</td>
<td style="vertical-align:middle;" headers="reading">
  [Generating Data from Models](https://zief0002.github.io/statistical-thinking/03-generating-data-from-models.html)
</td>
<td style="vertical-align:middle;" headers="activity">Generating Random Data: Pet Factory</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">5</td>
<td style="vertical-align:middle;" headers="date">Feb. 05</td>
<td style="vertical-align:middle;" headers="reading">
  [Monte Carlo Simulation](https://zief0002.github.io/statistical-thinking/04-monte-carlo-simulation.html)
</td>
<td style="vertical-align:middle;" headers="activity">Introduction to Monte Carlo Simulation</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">6</td>
<td style="vertical-align:middle;" headers="date">Feb. 10</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">Automating the Simulation Process</td>
</tr>

<tr style="background-color: #fffdc0;">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">7</td>
<td style="vertical-align:middle;" headers="date">Feb. 12</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">**Group Quiz 1**</td>
</tr>


<!-- Unit 02: MODELING SAMPLING VARIATION -->

<tr>
<td style="height: 50px; vertical-align: bottom;" colspan="5" headers="blank day date reading activity">**UNIT 02: MODELING SAMPLING VARIATION**</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="blank"></td>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="day">8</td>
<td style="vertical-align:middle;" rowspan=2 headers="date">Feb. 17</td>
<td style="vertical-align:middle;" rowspan=2 headers="reading"></td>
<td style="vertical-align:middle; background-color: #fffdc0;" headers="activity">
<!-- **Individual Exam 1** [Closed] -->
  [**Individual Exam 1**](https://docs.google.com/document/d/14icSqhEzHSNtTJeVjrVlW2vpACiF1l6EQEcPMH3TuZo/edit?usp=sharing) (due by 9:45am)
</td>
</tr>

<tr>
<td style="vertical-align:middle;" headers="activity">Monday Breakups</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">9</td>
<td style="vertical-align:middle;" headers="date">Feb. 19</td>
<td style="vertical-align:middle;" headers="reading">
  [Describing Distributions](https://zief0002.github.io/statistical-thinking/06-describing-distributions.html)
</td>
<td style="vertical-align:middle;" headers="activity">Features of Distributions</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">10</td>
<td style="vertical-align:middle;" headers="date">Feb. 24</td>
<td style="vertical-align:middle;" headers="reading">
  [Modeling Sampling Variation](https://zief0002.github.io/statistical-thinking/05-modeling-sampling-variation.html)
</td>
<td style="vertical-align:middle;" headers="activity">Helper or Hinderer</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">11</td>
<td style="vertical-align:middle;" headers="date">Feb. 26</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">Comparing Handspans</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">12</td>
<td style="vertical-align:middle;" headers="date">Mar. 03</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">Lead Exposure in Children</td>
</tr>


<tr style="background-color: #fffdc0">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">13</td>
<td style="vertical-align:middle;" headers="date">Mar. 05</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">**Group Quiz 2**</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day"></td>
<td style="vertical-align:middle;"headers="date">Mar. 10.</td>
<td style="vertical-align:middle;" colspan=2 headers="reading activity">NO CLASS---Spring Break 🎊 🛌 🎉 </td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day"></td>
<td style="vertical-align:middle;"headers="date">Mar. 12.</td>
<td style="vertical-align:middle;" colspan=2 headers="reading activity">NO CLASS---Spring Break 🎊 🛌 🎉 </td>
</tr>

<!-- Unit 03: EXPERIMENTAL VARIATION AND THE RANDOMIZATION TEST -->

<tr>
<td style="height: 50px; vertical-align: bottom;" colspan="5" headers="blank day date reading activity">
  **UNIT 03: EXPERIMENTAL VARIATION AND THE RANDOMIZATION TEST**
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="blank"></td>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="day">14</td>
<td style="vertical-align:middle;" rowspan=2 headers="date">Mar. 17</td>
<td style="vertical-align:middle;" rowspan=2 headers="reading"></td>
<td style="background-color: #fffdc0" headers="activity">
  <!-- **Individual Exam 2** [Closed] -->
  [**Individual Exam 2**](https://docs.google.com/document/d/14icSqhEzHSNtTJeVjrVlW2vpACiF1l6EQEcPMH3TuZo/edit?usp=sharing) (due by 9:45am)
</td>
</tr>

<tr>
<td style="vertical-align:middle;" headers="activity">Memorization</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">15</td>
<td style="vertical-align:middle;" headers="date">Mar. 19</td>
<td style="vertical-align:middle;" headers="reading">
  [Experimental Variation and the Randomization Test](https://zief0002.github.io/statistical-thinking/07-experimental-variation-and-the-randomization-test.html)
</td>
<td style="vertical-align:middle;" headers="activity">Memorization with TinkerPlots</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">16</td>
<td style="vertical-align:middle;" headers="date">Mar. 24</td>
<td style="vertical-align:middle;" headers="reading">
  [Internal Validity Evidence and Random Assignment](https://zief0002.github.io/statistical-thinking/09-internal-validity-evidence-and-random-assignment.html)
</td>
<td style="vertical-align:middle;" headers="activity">Sleep Deprivation</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">17</td>
<td style="vertical-align:middle;" headers="date">Mar. 26</td>
<td style="vertical-align:middle;" headers="reading">
  [Quantifying Results: p-Value](https://zief0002.github.io/statistical-thinking/08-quantifying-results-p-value.html)
</td>
<td style="vertical-align:middle;" headers="activity">Contagious Yawns</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">18</td>
<td style="vertical-align:middle;" headers="date">Mar. 31</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="acivity">Speed Skating</td>
</tr>


<tr style="background-color: #fffdc0">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">19</td>
<td style="vertical-align:middle;" headers="date">Apr. 02</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">**Group Quiz 3**</td>
</tr>


<!-- Unit 04: SAMPLING VARIATION AND THE BOOTSTRAP TEST -->

<tr>
<td style="height: 50px; vertical-align: bottom;" colspan="5" headers="blank day date reading activity">
  **UNIT 04: SAMPLING VARIATION AND THE BOOTSTRAP TEST**
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="blank"></td>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="day">20</td>
<td style="vertical-align:middle;" rowspan=2 headers="date">Apr. 07</td>
<td style="vertical-align:middle;" rowspan=2 headers="reading">
  [Sampling Variation and the Bootstrap Test](https://zief0002.github.io/statistical-thinking/10-sampling-variation-and-the-bootstrap-test.html)
</td>
<td style="background-color: #fffdc0" headers="activity">
  <!-- **Individual Exam 3** [Closed]  -->
 [**Individual Exam 3**](https://docs.google.com/document/d/11YlNAgR1mrss81v5YEJcozwdaF46cRil/edit?usp=sharing&ouid=100796696879019680143&rtpof=true&sd=true) (due by 9:45am)
</td>
</tr>


<tr>
<td headers="activity">Gettysburg Address</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">21</td>
<td style="vertical-align:middle;" headers="date">Apr. 09</td>
<td style="vertical-align:middle;" headers="reading">
  [Observational Studies and the Bootstrap Test](https://zief0002.github.io/statistical-thinking/13-observational-studies-and-the-bootstrap-test.html)<br />
  [External Validity Evidence and Random Sampling](https://zief0002.github.io/statistical-thinking/11-external-validity-evidence-and-random-sampling.html)
</td>
<td style="vertical-align:middle;" headers="activity">Murderous Nurse</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">22</td>
<td style="vertical-align:middle;" headers="date">Apr. 14</td>
<td style="vertical-align:middle;" headers="reading">
  [Validity Evidence and Inferences](https://zief0002.github.io/statistical-thinking/12-validity-evidence-and-inferences.html)
</td>
<td style="vertical-align:middle;" headers="activity">Movie Sequels</td>
</tr>



<tr style="background-color: #fffdc0">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">23</td>
<td style="vertical-align:middle;" headers="date">Apr. 16</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">**Group Quiz 4**</td>
</tr>


<!-- Unit 05: ESTIMATING UNCERTAINTY -->

<tr>
<td style="height: 50px; vertical-align: bottom;" colspan="5" headers="blank day date reading activity">
  **UNIT 05: ESTIMATING UNCERTAINTY**
</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="blank"></td>
<td align="center" style="vertical-align:middle;" rowspan=2 headers="day">24</td>
<td style="vertical-align:middle;" rowspan=2 headers="date">Apr. 21</td>
<td style="vertical-align:middle;" rowspan=2 headers="reading"></td>
<td style="background-color: #fffdc0" headers="activity">
  <!-- **Individual Exam 4** [Closed] -->
  [**Individual Exam 4**](https://docs.google.com/document/d/18tK0Ozi8ePfBewOAocbGYGTOdPq-cHeD/edit?usp=sharing&ouid=100796696879019680143&rtpof=true&sd=true) (due by 9:45am)
</td>
</tr>


<tr>
<td headers="activity">Kissing the 'Right' Way</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">25</td>
<td style="vertical-align:middle;"  headers="date">Apr. 23</td>
<td style="vertical-align:middle;" headers="reading">
  [Estimating Uncertainty](https://zief0002.github.io/statistical-thinking/14-estimating-uncertainty.html)
</td>
<td style="vertical-align:middle;" headers="activity">Cuddling Preferences</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">26</td>
<td style="vertical-align:middle;" headers="date">Apr. 28</td>
<td style="vertical-align:middle;" headers="reading">
  [Uncertainty and Bias](https://zief0002.github.io/statistical-thinking/15-uncertainty-and-bias.html)
</td>
<td style="vertical-align:middle;" headers="activity">Minnesota College Debt</td>
</tr>


<tr>
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">27</td>
<td style="vertical-align:middle;" headers="date">Apr. 30</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">Comparing Cuddling Preferences</td>
</tr>


<tr style="background-color: #fffdc0">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day">28</td>
<td style="vertical-align:middle;" headers="date">May. 05</td>
<td style="vertical-align:middle;" headers="reading"></td>
<td style="vertical-align:middle;" headers="activity">**Group Quiz 5**</td>
</tr>


<tr style="background-color: #fffdc0">
<td align="center" style="vertical-align:middle;" headers="blank"></td>
<td align="center" style="vertical-align:middle;" headers="day"></td>
<td style="vertical-align:middle;" colspan=3  headers="date reading activity">
  <!-- **Individual Exam 5** (due by 12:00pm on May 05) [Closed]  -->
  [**Individual Exam 5**](https://docs.google.com/document/d/1D4DjuC5YG7UO2NXJ4hm0Kzoax3PZ2kFr/edit?usp=sharing&ouid=100796696879019680143&rtpof=true&sd=true) (due by 12:00pm on May 07)
</td>
</tr>


</tbody>
</table>   






<!-- ### Feb. 10: More Quarto---Citations, Equations, Creating Tables with `gt` -->

<!-- - [Notes: Citations](notes/03-more-quarto.html) <br /> -->
<!-- - [Notes: Creating Tables ](notes/03-creating-tables.html) <br /> -->
<!-- - [QMD Document: Citations](https://raw.githubusercontent.com/zief0002/fluffy-ants/main/notes/03-more-quarto.qmd) -->
<!-- - [QMD Document: Creating Tables](https://raw.githubusercontent.com/zief0002/fluffy-ants/main/notes/03-creating-tables.qmd) -->




